### ISSUE TITLE
Почитай внимательно задание 

### ISSUE THREAD

**Issue by Muxamedin** [unoplus/hillel_2021#1]
https://github.com/unoplus/hillel_2021/blob/039f3b3becf5a4bc9ed84ec8ae29d5cdcaa6688b/Lesson_03/change_var.py#L3
В задании как раз исключен этот  способ выполнения 
В задании просится предложить есще один способ обмена целочисленными значениями :)

**Comment by unoplus** [comment]
Поменял переменные по другому, но не уверен, что это можно не считать множественным присваеванием...

**Comment by unoplus** [comment]
Касательно сортировки матрицы.
Переделал работу. Ошибка возникла из-за неясности условий задачи, как я смотрю по оценкам, не я один не понял что именно нужно сортировать.
Но это ладно, зато теперь я могу сортировать хоть вверх, хоть в низ, хоть поперёк, хоть по диагонали, алгоритм мне ясен, не вижу проблем.
Касательно оценки, можно как-то пересдать эту работу или она так уже и останется, с той оценкой, что вы поставили, или вы сами что-то добавите, если всё верно в новом варианте?
Дополнительную задачу из ДЗ9, сдам уже с ДЗ10, хотя хотел сегодня...

**Comment by unoplus** [comment]
Да, ещё хотел попросить по материалу урока №10. Там не весь код быстрой сортировки, можно дополнить конспект?

**Comment by Muxamedin** [comment]
Добрий день. 
Есть еще 2 пересдачи. 
Вы самом кабинете можно прислать на пересдачу.

Добавил в 10м уроке слайд.

Mikel Bily
Staff Software Engineer
CloudBees, Inc.

**Comment by unoplus** [comment]
Добавил в девятый урок задание с фигурами, хотелось бы комментариев, всё ли верно.
Добавил в десятый урок треугольную последовательность через рекурсию. Я хотел сразу так делать, но потом ещё раз глянул в задание и увидел эти строка: "Попробуйте обойтись только одним циклом for". Для себя я понял, что это как обязательное условие решения именно через один цикл, потому так и сделал в первом варианте.

**Comment by Muxamedin** [comment]
Решение норм 

Так как на 9м уроке мы учили функции - могу я вас попросить обернуть решение для каждого из файлов  в функции?
А имена файлов можно оставить так как есть.
Мы как раз можем это использовать на сегодняшнем уроке который будет посвящен модулям и пакетам.



Mikel Bily

**Comment by unoplus** [comment]
Обернуть то конечно можно, но к уроку я не успею, т.к. я на работе, да ещё и без обеда, потому что мой обеденный час  весь уйдёт на дорогу на курсы.

**Comment by Muxamedin** [comment]
Ну ничего тогда не нужно 
Есть материал другой - используем его 

Mikel Bily

**Comment by unoplus** [comment]
Не знаю как открыть новый ишью, чтобы он был виден вам... Потому пишу сюда)
Сделал новый скриптик. Хотел чтобы вы его посмотрели, если будет желание и время, и завтра обсудить.
Есть важный вопрос по этому делу, но писать долго.
В 16 ДЗ файл response_links.py
