### ISSUE TITLE
Лишние преобразования типов, избыточность и другое

### ISSUE THREAD

**Issue by Muxamedin** [unoplus/hillel_2021#4]
Зачем эти преобразвания ?

https://github.com/unoplus/hillel_2021/blob/d690558f9a67c91e507157b0b4c50e76cee85eae/Lesson_04/num_int_neighb.py#L16
https://github.com/unoplus/hillel_2021/blob/d690558f9a67c91e507157b0b4c50e76cee85eae/Lesson_04/num_int_neighb.py#L19

так как мы проходили списки - рекомендую остановится на манипуляциях со строками
len(cmd) даст то же количество элементов что в варианте после преобразования числа в строке к списку 
https://github.com/unoplus/hillel_2021/blob/d690558f9a67c91e507157b0b4c50e76cee85eae/Lesson_04/num_int_neighb.py#L16

Прошу обратить внимание на вывод который просится в задаче 
https://github.com/unoplus/hillel_2021/blob/c1bbfb2ef136584d124e4ee89519e600d0f297eb/Lesson_04/num_int_neighb.py#L25

**Comment by unoplus** [comment]
Эти преобразования "number = int(cmd) " нужны, потому что так поставлено условие задачи: "Ввести натуральное число и определить...".
Можно, конечно оформить это в виде "cmd = int(input("Введите натуральное число:  "), но это будет неправильно, т.к. пользователь может ввести не число и будет аварийное завершение, потому сначала мы должны проверить что ввёл пользователь и, если это число, то привести его к положенному типу, как сказано в условии. Я попытался всё это предусмотреть и правильно описать, но чётко попал в жизненное правило - инициатива наказуема...
Жаль, но я понял ваш посыл, впредь буду избегать собственных инициатив.
Если вы смотрели все мои скрипты, для этого урока, то у меня есть эти же примеры, где я использую строковые операции, а в примере, который для чисел, именно чисел, а не строкового представления чисел, строковые методы не подходят.
Хотел предоставить более полные версии, получил минус 5 баллов...
По поводу вывода результатов, ну тут да вывел немного иначе, переделал.

**Comment by Muxamedin** [comment]
Если говорить о проверке на натуральное число 
то вот определение https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%82%D1%83%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE
В задании нету определить что это натуральное 
если бы было то проверка не верна :)



isdigit() - Returns True if all characters in the string are digits

**Comment by unoplus** [comment]
Вот это уже по делу, но опять же это просто дополнительная задача, которую я сам себе поставил, как вы и писали, списки мы уже проходили и оцениваться, в теории, эти скрипты не должны. Я просто хотел, для себя попробовать и другие реализации, но выложил их сюда, для того чтобы получить какие-то замечания, если не справился.
Есть эти же задачи, решённые через строковые методы.
Но конечно, я не преподаватель...
Спасибо за подсказки выше.

**Comment by Muxamedin** [comment]
Извените что я сначала не проанализировал все скрипты и не выбрал самый нужный 

У меня сегодня на проверку было 4 ДЗ и в это время кипит задача по основной работе которую я стараюсь сдать вовремя и согласно требованиям 

Считаю что вы молодец и делаете правильно что выполняете больше чем требуется. У меня нету задачи занижать оценки у меня есть задача подсказать и сориентировать.  
Буду подсказывать и далее!

**Comment by unoplus** [comment]
Спасибо за понимание, в будущем, если буду подкладывать дополнительные скрипты, постараюсь их понятно обозначить, чтобы вы посмотрели на них, когда будет дополнительное время, если оно будет:)

**Comment by Muxamedin** [comment]
Я все смотрю - и сразу пытаюсь писать коментари 
- если оно не на оценку я не учитываю что бы небыло обид если что то не то 
уменя есть несколько обозначений 
1. рекомендация: это просто совет как в будущем делать 
2. Фраза в заголовке issue к строке  - тогда это разговор об ошибке в коде - которую можно исправить 
3.  Код не рабочий (или что то в этом роде ) - задание не выполнено
