### ISSUE TITLE
Нужно будет доработать :)

### ISSUE THREAD

**Issue by Muxamedin** [unoplus/hillel_2021#6]
Хорошая подача Игры!

https://github.com/unoplus/hillel_2021/blob/fa94d7007e0888dee43e3a37769e20c573f18ebf/Lesson_05/guess_num.py#L31

НО  в задаче сказано
 >> программа сообщает : это число больше или меньше или пользователь угадал.

Нету сообщения на больше меньше 

>> При вводе неправльного числа или не числа - выдвать сообщение об ошибке

при вводе -5  - говорит что это не число , стоит как то изменит смысл сообщения что бы было гармонично 

:)

**Comment by unoplus** [comment]
Доделал.
По поводу проверки на отрицательное число, это нужно сильно изгаляться, но мы ещё не учили всякие там эксепшоны... Может есть какой-то более простой способ из уже пройденных нами тем?

**Comment by Muxamedin** [comment]
>> При вводе неправльного числа или не числа - выдвать сообщение об ошибке игрока и считать как попытка.

Достаточно указать правильное сообщение 

Aх ты жалкий мешок костей, тебе  разрешено вводить число  от 1 до 100, пробуй еще раз:

Скорее всего подобное сообщение будет более соответствовать реальности

Если все таки обнаруживать отрицательные числа 
то можно было бы как то пользоваться 
abs() фукцией
 и сравнивать результат с значением в переменной

**Comment by unoplus** [comment]
Добавил ваш вариант ответа, про abs() я думал, как думал и про float, но чтобы работать с ними нужно использовать исключения, что-то вроде
def number()
    if user_num:.isdigit():
        print(user_num)
    else:
       try:
            float(user_num)
            print(user_num)
       except ValueError:
             print(user_num)

Но мы не учили ни функции, ни эксепшоны....

**Comment by Muxamedin** [comment]
Да 
В этом случае - читаем коментарий номер один последнюю строку 
и мой предыдущый ответ с примером сообщения

**Comment by unoplus** [comment]
Так и сделал, спасибо) Кстати ваш ответ очень в духе, лучше даже не придумать сходу). А пока думать не когда, я на работе(
Спасибо!

**Comment by Muxamedin** [comment]
Я до сих пор смотрю мультики с  детьми или без :)

Но Футурама и Симпсоны  - это то что я могу смотреть много раз 


Mikel Bily
Staff Software Engineer
CloudBees, Inc.

**Comment by unoplus** [comment]
Проверил но 0, отрабатывает корректно, пишет, что 0 меньше загаданного числа, как и должно быть.
