### ISSUE TITLE
Метод  класса обрабатывает глобальную переменную хотя на вход получает ее же значение 

### ISSUE THREAD

**Issue by Muxamedin** [unoplus/hillel_2021#9]
https://github.com/unoplus/hillel_2021/blob/86a0b2d41efcf4da0ec83ced74f98aedf0d0a759/Lesson_16/buffer.py#L22

Предлагаю обрабатывать все таки args 

![image](https://user-images.githubusercontent.com/4419752/132921000-664a9460-9396-414c-a0e8-2a846ef7aa07.png)

а значения передавать за счет разименования списка 

![image](https://user-images.githubusercontent.com/4419752/132921103-426e2845-0b9e-4eb2-832a-1294dca89226.png)

На вход поступает (последовательность элементов списка)набор значений а не список 
тогда как  args хранит эти  значения в виде кортежа

**Comment by unoplus** [comment]
Типа так? Я просто не совсем понимаю, чем набор лучше? Тем что нет одинаковых цифр? И вот это разыменование, я не понимаю почему список, ну или набор, как сейчас, упаковывается ещё раз в список, при передаче в класс? Первый раз когда делал, я аргс и использовал, но прогонял просто через два фора... Чтобы избавится от "упаковочного" списка...
